export const SET_LOGIN_STATE = 'SET_LOGIN_STATE';
export const SIGN_UP = 'SIGN_UP';
export const FORGOT_PASSWORD = 'FORGOT_PASSWORD';

export const NAVIGATION_LOGIN = 'NAVIGATION_LOGIN';
export const NAVIGATION_SIGNUP = 'NAVIGATION_SIGNUP';
export const NAVIGATION_SCAN_ID = 'NAVIGATION_SCAN_ID';
export const NAVIGATION_SCAN_QR = 'NAVIGATION_SCAN_QR';
export const NAVIGATION_PROFILE = 'NAVIGATION_PROFILE';
export const NAVIGATION_PATIENT_HISTORY = 'NAVIGATION_PATIENT_HISTORY';
export const NAVIGATION_PATIENT_DETAILS = 'NAVIGATION_PATIENT_DETAILS';
export const NAVIGATION_HOSPITAL_LIST = 'NAVIGATION_HOSPITAL_LIST';
export const NAVIGATION_FORGOT_PASSWORD = 'NAVIGATION_FORGOT_PASSWORD';

export const SET_NOTIFICATION = 'SET_NOTIFICATION';

export const ADD_PATIENT_HISTORY = 'ADD_PATIENT_HISTORY';
export const CLEAR_PATIENT_HISTORY = 'CLEAR_PATIENT_HISTORY';
export const SET_SELECTED_PATIENT = 'SET_SELECTED_PATIENT';

export const SET_HOSPITALS = 'SET_HOSPITALS';
export const SET_SELECTED_HOSPITAL = 'SET_SELECTED_HOSPITAL';